/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package absensiRFID.GUI;
import absensiRFID.panel.SiswaPanel;
import absensiRFID.panel.PenggunaPanel;
import absensiRFID.panel.DashboardPanel;


import com.mycompany.rfid_absensi_siswa.object.Siswa;
import com.mycompany.rfid_absensi_siswa.object.SiswaService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author organizer
 */

public class AdminPage extends javax.swing.JFrame {
    
    // Ganti 'Siswa' dengan nama class model kamu jika beda 

    private final SiswaService siswaService = new SiswaService();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPage.class.getName());

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();

        pContent.setLayout(new java.awt.BorderLayout());

    // tampil dashboard pertama kali
        pContent.removeAll();
        pContent.add(new DashboardPanel(), java.awt.BorderLayout.CENTER);
        pContent.revalidate();
        pContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pIcon = new javax.swing.JPanel();
        iconBook = new javax.swing.JLabel();
        txtSchool = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnSiswa = new javax.swing.JButton();
        btnLapor = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPengguna = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        panelUtama = new javax.swing.JPanel();
        pHeader = new javax.swing.JPanel();
        jDaftar = new javax.swing.JLabel();
        jSmart = new javax.swing.JLabel();
        pContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 800));

        pIcon.setBackground(new java.awt.Color(33, 47, 61));

        iconBook.setBackground(new java.awt.Color(0, 153, 255));
        iconBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png"))); // NOI18N

        txtSchool.setBackground(new java.awt.Color(0, 102, 255));
        txtSchool.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSchool.setForeground(new java.awt.Color(255, 255, 255));
        txtSchool.setText("School Admin");

        javax.swing.GroupLayout pIconLayout = new javax.swing.GroupLayout(pIcon);
        pIcon.setLayout(pIconLayout);
        pIconLayout.setHorizontalGroup(
            pIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSchool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pIconLayout.setVerticalGroup(
            pIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pIconLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(iconBook))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pIconLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        btnDashboard.setBackground(new java.awt.Color(52, 73, 94));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnDashboard.setText("DASHBOARD");
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnSiswa.setBackground(new java.awt.Color(52, 73, 94));
        btnSiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addUser.png"))); // NOI18N
        btnSiswa.setText("DATA SISWA");
        btnSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiswaActionPerformed(evt);
            }
        });

        btnLapor.setBackground(new java.awt.Color(52, 73, 94));
        btnLapor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLapor.setForeground(new java.awt.Color(255, 255, 255));
        btnLapor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N
        btnLapor.setText("LAPORAN");
        btnLapor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(52, 73, 94));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnPengguna.setBackground(new java.awt.Color(52, 73, 94));
        btnPengguna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPengguna.setForeground(new java.awt.Color(255, 255, 255));
        btnPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengguna.png"))); // NOI18N
        btnPengguna.setText("DATA PENGGUNA");
        btnPengguna.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenggunaActionPerformed(evt);
            }
        });

        btnAttendance.setBackground(new java.awt.Color(52, 73, 94));
        btnAttendance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAttendance.setForeground(new java.awt.Color(255, 255, 255));
        btnAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/attendance.png"))); // NOI18N
        btnAttendance.setText("ATTENDANCE");
        btnAttendance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addComponent(btnLapor, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLapor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));
        panelUtama.setLayout(new java.awt.BorderLayout());

        pHeader.setBackground(new java.awt.Color(44, 62, 80));

        jDaftar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jDaftar.setForeground(new java.awt.Color(255, 255, 255));
        jDaftar.setText("PENDAFTARAN SISWA ");

        jSmart.setBackground(new java.awt.Color(204, 204, 204));
        jSmart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSmart.setForeground(new java.awt.Color(255, 255, 255));
        jSmart.setText("SMART ATTENDANCE");

        javax.swing.GroupLayout pHeaderLayout = new javax.swing.GroupLayout(pHeader);
        pHeader.setLayout(pHeaderLayout);
        pHeaderLayout.setHorizontalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDaftar)
                    .addComponent(jSmart))
                .addContainerGap(835, Short.MAX_VALUE))
        );
        pHeaderLayout.setVerticalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHeaderLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jDaftar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSmart)
                .addContainerGap())
        );

        panelUtama.add(pHeader, java.awt.BorderLayout.PAGE_START);

        pContent.setLayout(new java.awt.BorderLayout());
        panelUtama.add(pContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiswaActionPerformed
        pContent.removeAll();
        pContent.add(new SiswaPanel(), java.awt.BorderLayout.CENTER);
        pContent.revalidate();
        pContent.repaint();

        jDaftar.setText("DATA SISWA");
    }//GEN-LAST:event_btnSiswaActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        pContent.removeAll();
        pContent.add(new DashboardPanel(), java.awt.BorderLayout.CENTER);
        pContent.revalidate();
        pContent.repaint();

        jDaftar.setText("DASHBOARD");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnLaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporActionPerformed

    private void btnPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenggunaActionPerformed
            pContent.removeAll();
            pContent.add(new PenggunaPanel(), java.awt.BorderLayout.CENTER);
            pContent.revalidate();
            pContent.repaint();

            jDaftar.setText("DATA PENGGUNA");
    }//GEN-LAST:event_btnPenggunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(() -> {
        new AdminPage().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLapor;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPengguna;
    private javax.swing.JButton btnSiswa;
    private javax.swing.JLabel iconBook;
    private javax.swing.JLabel jDaftar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSmart;
    private javax.swing.JPanel pContent;
    private javax.swing.JPanel pHeader;
    private javax.swing.JPanel pIcon;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JLabel txtSchool;
    // End of variables declaration//GEN-END:variables
}
