/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package absensiRFID.GUI;

import com.mycompany.rfid_absensi_siswa.object.Admin;
import absensiRFID.services.AdminService;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author organizer
 */
public class LoginPage extends javax.swing.JFrame {

    private boolean showPassword = false;
    private final AdminService adminService = new AdminService();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();

        txtPassword.setEchoChar((char) 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLogin = new javax.swing.JLabel();
        titleSmart = new javax.swing.JLabel();
        titleWelcome = new javax.swing.JLabel();
        titleEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        titlePassword = new javax.swing.JLabel();
        lblEye = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        bgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/idcard.png"))); // NOI18N
        getContentPane().add(iconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 590, 370));

        titleSmart.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleSmart.setForeground(new java.awt.Color(255, 255, 255));
        titleSmart.setText(" SMART ATTENDANCE RFID");
        getContentPane().add(titleSmart, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 480, 70));

        titleWelcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleWelcome.setForeground(new java.awt.Color(204, 204, 204));
        titleWelcome.setText("Welcome Back! Please Login First");
        getContentPane().add(titleWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, 270, -1));

        titleEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleEmail.setForeground(new java.awt.Color(255, 255, 255));
        titleEmail.setText("Email");
        getContentPane().add(titleEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 50, -1));

        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setText("Masukan Email");
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 315, 330, 42));

        titlePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titlePassword.setForeground(new java.awt.Color(255, 255, 255));
        titlePassword.setText("Password");
        getContentPane().add(titlePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, -1, -1));

        lblEye.setForeground(new java.awt.Color(255, 255, 255));
        lblEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye.png"))); // NOI18N
        lblEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEyeMouseClicked(evt);
            }
        });
        getContentPane().add(lblEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 440, -1, -1));

        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setText("Masukan Password");
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 330, 42));

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 190, 40));

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bglogin.png"))); // NOI18N
        bgLogin.setText("jLabel2");
        getContentPane().add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // 1. Ambil input dari user
        String username = txtEmail.getText().trim();
        String password = String.valueOf(txtPassword.getPassword()).trim();

        // VALIDASI
        if (username.isEmpty()
                || password.isEmpty()
                || username.equals("Masukan Email")
                || password.equals("Masukan Password")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Username dan Password wajib diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {

            Admin admin = adminService.login(username, password);
            
            System.out.println(admin);

            if (admin != null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Login berhasil!\nSelamat datang "
                        + admin.getNamaLengkap()
                );

                new AdminPage().setVisible(true);

                this.dispose();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Username atau Password salah!",
                        "Login Gagal",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked

        if (txtEmail.getText().trim().equals("Masukan Email")) {

            txtEmail.setText("");
            txtEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked

        String pass = String.valueOf(txtPassword.getPassword());

        if (pass.trim().equals("Masukan Password")) {

            txtPassword.setText("");
            txtPassword.setForeground(Color.BLACK);

            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void lblEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEyeMouseClicked

        if (showPassword == false) {

            txtPassword.setEchoChar((char) 0);

            lblEye.setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/img/hidden.png")
            ));

            showPassword = true;

        } else {

            txtPassword.setEchoChar('*');

            lblEye.setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/img/eye.png")
            ));

            showPassword = false;
        }
    }//GEN-LAST:event_lblEyeMouseClicked

    /**
     * @param args the command line argumentsFFILE
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel iconLogin;
    private javax.swing.JLabel lblEye;
    private javax.swing.JLabel titleEmail;
    private javax.swing.JLabel titlePassword;
    private javax.swing.JLabel titleSmart;
    private javax.swing.JLabel titleWelcome;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
