/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package absensiRFID.panel;

import absensiRFID.services.PegawaiService;
import com.mycompany.rfid_absensi_siswa.object.Pegawai;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author organizer
 */
public class PenggunaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PenggunaPanel
     */
    public PenggunaPanel() {
        initComponents();
        
        showData();
    }
    
    public void showData() {
        PegawaiService service = new PegawaiService();
        service.tampilPegawai(jTable1, txtCari.getText());
    }
    
    private void resetForm() {
        txtId.setText("");
        txtNama.setText("");
        pJabatan.setSelectedIndex(0);
        txtNoHp.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInput = new javax.swing.JPanel();
        titleId = new javax.swing.JLabel();
        titleNama = new javax.swing.JLabel();
        titleJurusan = new javax.swing.JLabel();
        titleHp = new javax.swing.JLabel();
        panelId = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        panelNama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        panelJabatan = new javax.swing.JPanel();
        pJabatan = new javax.swing.JComboBox<>();
        panelNoHp = new javax.swing.JPanel();
        txtNoHp = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        panelCari = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1097, 762));

        pInput.setBackground(new java.awt.Color(255, 255, 255));
        pInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pendaftaran Siswa"));
        pInput.setPreferredSize(new java.awt.Dimension(250, 300));
        pInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleId.setBackground(new java.awt.Color(255, 255, 255));
        titleId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleId.setText("ID PEGAWAI");
        pInput.add(titleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 20));

        titleNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleNama.setText("NAMA");
        titleNama.setMaximumSize(new java.awt.Dimension(24, 20));
        titleNama.setMinimumSize(new java.awt.Dimension(24, 20));
        pInput.add(titleNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 100, 20));

        titleJurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleJurusan.setText("JABATAN");
        pInput.add(titleJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        titleHp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleHp.setText("NO HANDPHONE");
        pInput.add(titleHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, -1));

        panelId.setBackground(new java.awt.Color(255, 255, 255));
        panelId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelId.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/uid.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        panelId.add(jLabel1, java.awt.BorderLayout.WEST);

        txtId.setBorder(null);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        panelId.add(txtId, java.awt.BorderLayout.CENTER);

        pInput.add(panelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 40));

        panelNama.setBackground(new java.awt.Color(255, 255, 255));
        panelNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelNama.setPreferredSize(new java.awt.Dimension(300, 40));
        panelNama.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nama.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        panelNama.add(jLabel3, java.awt.BorderLayout.LINE_START);

        txtNama.setBorder(null);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        panelNama.add(txtNama, java.awt.BorderLayout.CENTER);

        pInput.add(panelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 250, 40));

        panelJabatan.setBackground(new java.awt.Color(255, 255, 255));
        panelJabatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelJabatan.setPreferredSize(new java.awt.Dimension(220, 40));
        panelJabatan.setLayout(new java.awt.BorderLayout());

        pJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jabatan", "GURU", "ADMIN", "TATA USAHA" }));
        pJabatan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pJabatan.setFocusable(false);
        pJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pJabatanActionPerformed(evt);
            }
        });
        panelJabatan.add(pJabatan, java.awt.BorderLayout.CENTER);

        pInput.add(panelJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 220, 40));

        panelNoHp.setBackground(new java.awt.Color(255, 255, 255));
        panelNoHp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelNoHp.setLayout(new java.awt.BorderLayout());

        txtNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHpActionPerformed(evt);
            }
        });
        panelNoHp.add(txtNoHp, java.awt.BorderLayout.CENTER);

        pInput.add(panelNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 220, 40));

        btnSave.setBackground(new java.awt.Color(46, 204, 113));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pInput.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 120, 35));

        btnEdit.setBackground(new java.awt.Color(241, 196, 15));
        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pInput.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 120, 35));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        pInput.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 120, 35));

        panelCari.setBackground(new java.awt.Color(255, 255, 255));
        panelCari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelCari.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        panelCari.add(jLabel2, java.awt.BorderLayout.LINE_START);

        txtCari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        panelCari.add(txtCari, java.awt.BorderLayout.CENTER);

        pInput.add(panelCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 250, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID PEGAWAI", "NAMA", "JABATAN", "NO HP"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pInput.getAccessibleContext().setAccessibleName("Data Pegawai Sekolah");
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void pJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pJabatanActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        // 1. Ambil data dari semua field input
        String id = txtId.getText();
        String nama = txtNama.getText();
        String jabatan = pJabatan.getSelectedItem().toString();
        String noHp = txtNoHp.getText();

        // Validasi: Jangan biarkan data kosong masuk ke DB
        if (id.isEmpty() || nama.isEmpty() || noHp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data wajib diisi!");
            return;
        }
        
        Pegawai p = new Pegawai();
        
        p.setIdPegawai(id);
        p.setNamaPegawai(nama);
        p.setJabatan(jabatan);
        p.setNoHp(noHp);

        PegawaiService service =
        new PegawaiService();

        service.tambahPegawai(p);

        JOptionPane.showMessageDialog(
            this,
            "Data Pegawai berhasil disimpan!"
        );

        showData();
        resetForm();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
 
            String id = txtId.getText();
            String nama = txtNama.getText();
            String jabatan = pJabatan.getSelectedItem().toString();
            String noHp = txtNoHp.getText();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data yang akan diedit!");
            return;
        }

        Pegawai p = new Pegawai();

        p.setIdPegawai(id);
        p.setNamaPegawai(nama);
        p.setJabatan(jabatan);
        p.setNoHp(noHp);

        PegawaiService service = new PegawaiService();
        service.updatePegawai(p);

        JOptionPane.showMessageDialog(this,
                "Data berhasil diupdate!");

        showData();
        resetForm();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Error : " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       showData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int column = jTable1.columnAtPoint(evt.getPoint());
        int row = jTable1.getSelectedRow();

        // Cek apakah yang diklik adalah kolom ACTION (indeks 4)
        if (row != -1) {
            // Buat pilihan menu muncul (Edit atau Delete)
            Object[] options = {"Edit", "Delete", "Batal"};
            int choice = JOptionPane.showOptionDialog(this,
                "Pilih aksi untuk data: " + jTable1.getValueAt(row, 1),
                "Action Menu",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);

            if (choice == 0) { // Jika pilih EDIT
                aksiEdit(row);
            } else if (choice == 1) { // Jika pilih DELETE
                aksiDelete(row);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void aksiEdit(int row) {
        txtId.setText(
            jTable1.getValueAt(row, 0).toString());
        txtNama.setText(
                jTable1.getValueAt(row, 1).toString());
        pJabatan.setSelectedItem(
                jTable1.getValueAt(row, 2).toString());
        txtNoHp.setText(
            jTable1.getValueAt(row, 3).toString());
    }

    private void aksiDelete(int row) {
        String id =
            jTable1.getValueAt(row, 0).toString();
        PegawaiService service =
                new PegawaiService();
        service.hapusPegawai(id);
        JOptionPane.showMessageDialog(this,
                "Data berhasil dihapus");
        showData();
        resetForm();
    }
    private void txtNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHpActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        DefaultTableModel model =
            (DefaultTableModel) jTable1.getModel();

        TableRowSorter<DefaultTableModel> sorter =
                new TableRowSorter<>(model);

        jTable1.setRowSorter(sorter);

        sorter.setRowFilter(
                RowFilter.regexFilter("(?i)" + txtCari.getText())
        );
    }//GEN-LAST:event_txtCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pInput;
    private javax.swing.JComboBox<String> pJabatan;
    private javax.swing.JPanel panelCari;
    private javax.swing.JPanel panelId;
    private javax.swing.JPanel panelJabatan;
    private javax.swing.JPanel panelNama;
    private javax.swing.JPanel panelNoHp;
    private javax.swing.JLabel titleHp;
    private javax.swing.JLabel titleId;
    private javax.swing.JLabel titleJurusan;
    private javax.swing.JLabel titleNama;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHp;
    // End of variables declaration//GEN-END:variables
}

