/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package absensiRFID.panel;

import absensiRFID.DAO.GenericDAO;
import org.bson.Document;
import javax.swing.JOptionPane;
import com.mycompany.rfid_absensi_siswa.object.Siswa;
import com.mycompany.rfid_absensi_siswa.object.SiswaService;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author organizer
 */
public class SiswaPanel extends javax.swing.JPanel {
    
    private final SiswaService siswaService = new SiswaService();
    GenericDAO<Document> siswaDAO =
            new GenericDAO<>("Siswa", Document.class);
    
    public SiswaPanel() {
        initComponents();
        
        refreshTable();
        resetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInput = new javax.swing.JPanel();
        titleUid = new javax.swing.JLabel();
        titleRfidId = new javax.swing.JLabel();
        titleNama = new javax.swing.JLabel();
        titleJurusan = new javax.swing.JLabel();
        titleKelas = new javax.swing.JLabel();
        panelUid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUid = new javax.swing.JTextField();
        panelRfid = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        panelNama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        panelJurusan = new javax.swing.JPanel();
        pJurusan = new javax.swing.JComboBox<>();
        panelKelas = new javax.swing.JPanel();
        pKelas = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        pInput.setBackground(new java.awt.Color(255, 255, 255));
        pInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pendaftaran Siswa"));
        pInput.setPreferredSize(new java.awt.Dimension(250, 300));
        pInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleUid.setBackground(new java.awt.Color(255, 255, 255));
        titleUid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleUid.setText("USER ID");
        pInput.add(titleUid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 20));

        titleRfidId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleRfidId.setText("UID RFID");
        titleRfidId.setPreferredSize(new java.awt.Dimension(220, 35));
        pInput.add(titleRfidId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 100, 20));

        titleNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleNama.setText("NAMA");
        titleNama.setMaximumSize(new java.awt.Dimension(24, 20));
        titleNama.setMinimumSize(new java.awt.Dimension(24, 20));
        pInput.add(titleNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 100, 20));

        titleJurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleJurusan.setText("JURUSAN");
        pInput.add(titleJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        titleKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleKelas.setText("KELAS");
        pInput.add(titleKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        panelUid.setBackground(new java.awt.Color(255, 255, 255));
        panelUid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelUid.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/uid.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        panelUid.add(jLabel1, java.awt.BorderLayout.WEST);

        txtUid.setBorder(null);
        txtUid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUidActionPerformed(evt);
            }
        });
        panelUid.add(txtUid, java.awt.BorderLayout.CENTER);

        pInput.add(panelUid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 40));

        panelRfid.setBackground(new java.awt.Color(255, 255, 255));
        panelRfid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelRfid.setPreferredSize(new java.awt.Dimension(220, 35));
        panelRfid.setLayout(new java.awt.BorderLayout());

        txtId.setBorder(null);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        panelRfid.add(txtId, java.awt.BorderLayout.CENTER);

        pInput.add(panelRfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 220, 40));

        panelNama.setBackground(new java.awt.Color(255, 255, 255));
        panelNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelNama.setPreferredSize(new java.awt.Dimension(300, 40));
        panelNama.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nama.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        panelNama.add(jLabel3, java.awt.BorderLayout.LINE_START);

        txtNama.setBorder(null);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        panelNama.add(txtNama, java.awt.BorderLayout.CENTER);

        pInput.add(panelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 250, 40));

        panelJurusan.setBackground(new java.awt.Color(255, 255, 255));
        panelJurusan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelJurusan.setPreferredSize(new java.awt.Dimension(220, 40));
        panelJurusan.setLayout(new java.awt.BorderLayout());

        pJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jurusan", "MIPA", "IPS", "BAHASA DAN BUDAYA" }));
        pJurusan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pJurusan.setFocusable(false);
        pJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pJurusanActionPerformed(evt);
            }
        });
        panelJurusan.add(pJurusan, java.awt.BorderLayout.CENTER);

        pInput.add(panelJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 40));

        panelKelas.setBackground(new java.awt.Color(255, 255, 255));
        panelKelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelKelas.setLayout(new java.awt.BorderLayout());

        pKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kelas", "X", "XI", "XII" }));
        pKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pKelasActionPerformed(evt);
            }
        });
        panelKelas.add(pKelas, java.awt.BorderLayout.CENTER);

        pInput.add(panelKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 220, 40));

        btnSave.setBackground(new java.awt.Color(46, 204, 113));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pInput.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 120, 35));

        btnEdit.setBackground(new java.awt.Color(241, 196, 15));
        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pInput.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 120, 35));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        pInput.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 120, 35));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_START);

        txtCari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        jPanel2.add(txtCari, java.awt.BorderLayout.CENTER);

        pInput.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 250, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "USERS ID", "UID RFID", "NAMA", "JURUSAN", "KELAS"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pInput, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUidActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void pJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pJurusanActionPerformed

    private void pKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pKelasActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        // 1. Ambil data dari semua field input
        String uid = txtUid.getText();
        String rfid = txtId.getText();
        String nama = txtNama.getText();
        String jurusan = pJurusan.getSelectedItem().toString();
        String kelas = pKelas.getSelectedItem().toString();
        showData("");

        // Validasi: Jangan biarkan data kosong masuk ke DB
        if (uid.isEmpty() || nama.isEmpty() || rfid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "UID dan Nama wajib diisi!");
            return;
        }

        /// 2. Proses Simpan
        try {
            String uri = "mongodb://localhost:27017";
            try (com.mongodb.client.MongoClient mongoClient = com.mongodb.client.MongoClients.create(uri)) {
                com.mongodb.client.MongoDatabase database = mongoClient.getDatabase("Absensi");
                com.mongodb.client.MongoCollection<org.bson.Document> collection = database.getCollection("Siswa");

                // 2. LOGIKA PENGONDISIAN (CEK DUPLIKASI)
                // Cari apakah idSiswa ATAU uidRfid sudah ada di database
                org.bson.Document cekId = collection.find(new org.bson.Document("idSiswa", uid)).first();
                org.bson.Document cekRfid = collection.find(new org.bson.Document("uidRfid", rfid)).first();

                if (cekId != null) {
                    JOptionPane.showMessageDialog(this, "Gagal! ID Siswa " + uid + " sudah terdaftar.", "Duplikasi Data", JOptionPane.WARNING_MESSAGE);
                } else if (cekRfid != null) {
                    JOptionPane.showMessageDialog(this, "Gagal! Kartu RFID " + rfid + " sudah digunakan siswa lain.", "Duplikasi Data", JOptionPane.WARNING_MESSAGE);
                } else {
                    // 3. Jika tidak ada duplikasi, baru jalankan simpan
                    org.bson.Document doc = new org.bson.Document("idSiswa", uid)
                    .append("namaLengkap", nama)
                    .append("kelasSiswa", kelas)
                    .append("jurusanSiswa", jurusan)
                    .append("uidRfid", rfid);

                    collection.insertOne(doc);
                    JOptionPane.showMessageDialog(this, "Data Siswa Berhasil Disimpan!");

                    refreshTable();
                    resetForm();
                }
            }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            // 1. Ambil data TERBARU yang sudah kamu ketik di kotak input
            String idSiswa = txtUid.getText(); // ID sebagai kunci
            String rfid = txtId.getText();
            String nama = txtNama.getText();
            String jurusan = pJurusan.getSelectedItem().toString();
            String kelas = pKelas.getSelectedItem().toString();

            // Validasi simpel: pastikan ID tidak kosong
            if (idSiswa.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!");
                return;
            }

            // 2. Bungkus data baru tersebut ke dalam Document
            org.bson.Document dataBaru = new org.bson.Document("idSiswa", idSiswa)
            .append("namaLengkap", nama)
            .append("kelasSiswa", kelas)
            .append("jurusanSiswa", jurusan)
            .append("uidRfid", rfid);

            // 3. SURUH DAO UNTUK UPDATE KE MONGODB
            // Cari yang "idSiswa"-nya sama, lalu timpa dengan dataBaru
            siswaDAO.update("idSiswa", idSiswa, dataBaru);

            // 4. Beri tahu user kalau berhasil
            JOptionPane.showMessageDialog(this, "Berhasil Update data: " + nama);

            // 5. Segarkan tampilan tabel agar nama baru muncul
            refreshTable();
            resetForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int column = jTable1.columnAtPoint(evt.getPoint());
        int row = jTable1.getSelectedRow();

        // Cek apakah yang diklik adalah kolom ACTION (indeks 4)
        if (row != -1) {
            // Buat pilihan menu muncul (Edit atau Delete)
            Object[] options = {"Edit", "Delete", "Batal"};
            int choice = JOptionPane.showOptionDialog(this,
                "Pilih aksi untuk data: " + jTable1.getValueAt(row, 1),
                "Action Menu",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);

            if (choice == 0) { // Jika pilih EDIT
                aksiEdit(row);
            } else if (choice == 1) { // Jika pilih DELETE
                aksiDelete(row);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();

        TableRowSorter<DefaultTableModel> sorter =
                new TableRowSorter<>(model);

        jTable1.setRowSorter(sorter);

        sorter.setRowFilter(
                RowFilter.regexFilter("(?i)" + txtCari.getText())
        );
    }//GEN-LAST:event_txtCariKeyReleased

   private void showData(String keyword) {
    refreshTable();
}

   private void refreshTable() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("USERS ID");
    model.addColumn("UID RFID");
    model.addColumn("NAMA");
    model.addColumn("JURUSAN");
    model.addColumn("KELAS");

    try {
        List<Siswa> daftarSiswa = siswaService.getAllSiswa();
        for (Siswa siswa : daftarSiswa) {
            model.addRow(new Object[]{
                siswa.getIdSiswa(),
                siswa.getUidRfid(),
                siswa.getNamaLengkap(),
                siswa.getJurusanSiswa(),
                siswa.getKelasSiswa()
            });
        }
        jTable1.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal refresh tabel: " + e.getMessage()
        );
    }
   }
    private void resetForm() {
    txtUid.setText("");
    txtId.setText("");
    txtNama.setText("");
    pJurusan.setSelectedIndex(0);
    pKelas.setSelectedIndex(0);
}

    private void aksiEdit(int row) {

    txtUid.setText(jTable1.getValueAt(row, 0).toString());
    txtId.setText(jTable1.getValueAt(row, 1).toString());
    txtNama.setText(jTable1.getValueAt(row, 2).toString());

    pJurusan.setSelectedItem(
            jTable1.getValueAt(row, 3).toString());

    pKelas.setSelectedItem(
            jTable1.getValueAt(row, 4).toString());
}

    private void aksiDelete(int row) {

    String idSiswa =
            jTable1.getValueAt(row, 0).toString();

    siswaService.hapusSiswa(idSiswa);

    refreshTable();
    resetForm();

    JOptionPane.showMessageDialog(this,
            "Data berhasil dihapus");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pInput;
    private javax.swing.JComboBox<String> pJurusan;
    private javax.swing.JComboBox<String> pKelas;
    private javax.swing.JPanel panelJurusan;
    private javax.swing.JPanel panelKelas;
    private javax.swing.JPanel panelNama;
    private javax.swing.JPanel panelRfid;
    private javax.swing.JPanel panelUid;
    private javax.swing.JLabel titleJurusan;
    private javax.swing.JLabel titleKelas;
    private javax.swing.JLabel titleNama;
    private javax.swing.JLabel titleRfidId;
    private javax.swing.JLabel titleUid;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUid;
    // End of variables declaration//GEN-END:variables

}
